Feature/support indirect share mode
openscilab/mybutton pull request #17
Opened 2024-05-23 09:08 UTC by F-Shahali

**Reference Issues/PRs**
#11 

**What does this implement/fix? Explain your changes.**
- add option to choose sharing mode (direct / indirect)
- add /share route for indirect sharing
- loading icon changed

2024-05-23 14:46 UTC, AHReccese requested changes

2024-05-23 14:46 UTC, AHReccese commented on src/Views/Layout/ShareModal/index.tsx
> +		return `http://localhost:3000/share/?service=${service_title}&subject=${subject}&link=${url}`;
why do we have this here?
@F-Shahali

2024-05-23 15:03 UTC, F-Shahali commented on src/Views/Layout/ShareModal/index.tsx
> +		return `http://localhost:3000/share/?service=${service_title}&subject=${subject}&link=${url}`;
My bad, it was for test mode. I forgot to replace `http://localhost:3000` with front domain. It's for indirect sharing.
I'll change it.

2024-05-25 18:14 UTC, AHReccese requested changes
First, when I'm choosing the indirect mode in the dev environment, why the generated link is for production? Everything should be in the same environment. 
Secondly, there is no need to use the `www` CNAME tag. Use the A tag, like `https://dev.mybutton.click`

2024-05-26 19:46 UTC, AHReccese approved these changes
LGTM

2024-05-26 19:46 UTC, merged