add static files
openscilab/mybutton pull request #18
Opened 2024-06-14 20:21 UTC by F-Shahali

2024-06-15 08:04 UTC, AHReccese requested changes

2024-06-15 08:04 UTC, AHReccese commented on CHANGELOG.md
> +-   Choose direct or indirect sharing mode
@F-Shahali 
put them all in the "Added" part.
Every single thing for the first release belongs to the "Added" part.

2024-06-15 08:06 UTC, AHReccese commented
@F-Shahali 
Also, fulfil the description of the PR.

2024-06-15 08:38 UTC, F-Shahali commented on CHANGELOG.md
> +-   Choose direct or indirect sharing mode
Yes, I think I have done exactly the same thing.

2024-06-16 18:52 UTC, AHReccese commented
@F-Shahali 
Let me know when you are done with this PR, so I take care of the rest.

2024-06-16 21:33 UTC, F-Shahali commented
> @F-Shahali Also, fulfill the description of the PR.

I just mentioned the files added in this PR.
Other documents have been added before.

2024-06-16 21:36 UTC, F-Shahali commented
> @F-Shahali Let me know when you are done with this PR, so I take care of the rest.

It's done. You can go ahead.

2024-06-16 23:17 UTC, AHReccese commented on README.md
> +Just fill an issue and describe it. We'll check it ASAP! or send an email to [info@openscilab.com](mailto:info@openscilab.com 'info@openscilab.com').
replace `info@` with `mybutton@`

2024-06-16 23:19 UTC, AHReccese commented on .vscode/settings.json
Keep this file locally (add the `.vscode` directory to the `.gitignore` file)
As you know, This folder contains user-specific settings for Visual Studio Code.

2024-06-16 23:23 UTC, AHReccese commented
@sepandhaghighi 
Dear Sepand, Since we are about to release v0.1 of the MyButton project, and this PR addresses README.md and other standard documents to have in an open-source project, I would appreciate it if you too could kindly review this PR.

2024-06-17 22:41 UTC, sepandhaghighi requested changes
Thanks for your efforts 💯 

Take a look at my comments.
Also, don't forget `CNAME` file (Example : https://github.com/openscilab/openscilab.github.io/blob/gh-pages/CNAME)

2024-06-17 22:41 UTC, sepandhaghighi commented on README.md
> +## Table of contents
Remove TOC section from `README.md`

2024-06-17 22:41 UTC, sepandhaghighi commented on README.md
> -# mybutton
Add a title section and badge section to `README.md`. Something like this:

```
<div align="center">
    <h1>MyButton</h1>
    <br/>
    <a href="https://discord.gg/xxxx"><img src="https://img.shields.io/discord/xxxxxx.svg" alt="Discord Channel"></a>
    ...
</div>
```

I recommend checking out [Shields.io](https://shields.io/.)

2024-06-19 23:27 UTC, sepandhaghighi requested changes

2024-06-19 23:27 UTC, sepandhaghighi commented on README.md
> +[![TypeScript](https://img.shields.io/badge/TypeScript-007ACC?logo=typescript&style=for-the-badge)](https://www.typescriptlang.org/)
I recommend against using a combination of Markdown and HTML for badge links. Please replace these badges with HTML code.

2024-06-21 20:45 UTC, sepandhaghighi requested changes

2024-06-21 20:45 UTC, sepandhaghighi commented on README.md
> +  <img src="https://img.shields.io/badge/TypeScript-007ACC?logo=typescript&style=for-the-badge" alt="TypeScript"/>
@AHReccese I have a question: Is this the official badge for `TS`? I can't see the `TS` logo very clearly!
I suggest changing the background color of this badge.

2024-06-21 20:45 UTC, sepandhaghighi commented on README.md
> +  <img src="https://img.shields.io/badge/TypeScript-007ACC?logo=typescript&style=for-the-badge" alt="TypeScript"/>
<img src="https://img.shields.io/badge/TypeScript-007ACC?logo=typescript&style=for-the-badge" alt="TypeScript"/>

2024-06-21 22:23 UTC, AHReccese commented on README.md
> +  <img src="https://img.shields.io/badge/TypeScript-007ACC?logo=typescript&style=for-the-badge" alt="TypeScript"/>
Sorry, According to the hell amount of tasks, I forgot to update it previously, I noticed the difference but I forgot to update it. Thank you for your detailed review.

2024-06-24 13:18 UTC, sepandhaghighi approved these changes
LGTM 💯 
@AHReccese Please take a final look, if everything is okay `Squash/Merge` it after approval.

2024-06-24 17:15 UTC, AHReccese commented
@F-Shahali 
Are you done? if you do, please re-request for review.

2024-06-26 18:08 UTC, merged