add `constant.ts` version to `version_check.py`
openscilab/mybutton pull request #23
Opened 2024-07-05 15:00 UTC by AHReccese

`version_check.py` script updated [add website's footer version]

2024-07-05 23:46 UTC, sepandhaghighi requested changes
@AHReccese 

Please update `RELEASE.md`(item 2):
    1. `SECURITY.md`
    2. `otherfiles/version_check.py`
    3. `src/App/Config/constants.ts`
    
 Add `package.json` to `version_check.py` script

2024-07-06 10:31 UTC, F-Shahali approved these changes

2024-07-06 10:43 UTC, AHReccese commented
> @AHReccese
> 
> Please update `RELEASE.md`(item 2): 1. `SECURITY.md` 2. `otherfiles/version_check.py` 3. `src/App/Config/constants.ts`
> 
> Add `package.json` to `version_check.py` script

Sure thing, I applied them all.

2024-07-06 12:14 UTC, sepandhaghighi requested changes
@AHReccese Take a look at my comments 🔥

2024-07-06 12:14 UTC, sepandhaghighi commented on otherfiles/RELEASE.md
>  3. Update `CHANGELOG.md`
Add something like this:

4. Update `.github/ISSUE_TEMPLATE/bug_report.yml`
   1. Add new version tag to `MyButton version` dropbox options

2024-07-06 12:14 UTC, sepandhaghighi commented on otherfiles/RELEASE.md
>  3. Update `CHANGELOG.md`
Take a look at https://github.com/openscilab/pymilo/blob/main/otherfiles/RELEASE.md

2024-07-06 12:14 UTC, sepandhaghighi commented on otherfiles/RELEASE.md
`**Last Update: 2024-07-06**`

2024-07-14 05:09 UTC, AHReccese commented on otherfiles/RELEASE.md
applied

2024-07-14 05:09 UTC, AHReccese commented on otherfiles/RELEASE.md
>  3. Update `CHANGELOG.md`
applied

2024-07-14 09:40 UTC, sepandhaghighi requested changes

2024-07-14 09:40 UTC, sepandhaghighi commented on otherfiles/RELEASE.md
> +    2. `otherfiles/version_check.py`
Duplicate numbers.
1.
2.
3.
4.

2024-07-16 14:56 UTC, sepandhaghighi approved these changes
🔥

2024-07-16 14:56 UTC, merged