move build & version_check steps to github runners
openscilab/mybutton pull request #31
Opened 2024-09-18 22:25 UTC by AHReccese

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

#### Any other comments?

2024-09-19 17:06 UTC, F-Shahali approved these changes

2024-09-20 19:48 UTC, sepandhaghighi requested changes

2024-09-20 19:48 UTC, sepandhaghighi commented on CHANGELOG.md
> +- move `build` & `version_check` steps to `github runners`
Move

2024-09-21 21:42 UTC, sepandhaghighi approved these changes
🔥

2024-09-21 21:42 UTC, merged