Add/google analytics
openscilab/mybutton pull request #42
Opened 2024-10-18 17:15 UTC by AHReccese

#### Reference Issues/PRs
- Google Tag Manager installed
#### What does this implement/fix? Explain your changes.

#### Any other comments?

2024-10-18 22:55 UTC, sepandhaghighi requested changes

2024-10-18 22:55 UTC, sepandhaghighi commented on public/index.html
> -		<noscript>You need to enable JavaScript to run this app.</noscript>
Why did you remove this line?

2024-10-18 22:55 UTC, sepandhaghighi commented on public/index.html
> +		<!-- Google Tag Manager -->
Is it okay to add this script in the `head` section? Most websites suggest adding scripts like this to the end of the file.
Please double-check it

2024-10-18 23:23 UTC, AHReccese commented on public/index.html
> +		<!-- Google Tag Manager -->
<img width="567" alt="image" src="https://github.com/user-attachments/assets/f6d42e35-bb0d-43de-855b-ffefe1ded1fd">

2024-10-18 23:24 UTC, AHReccese commented on public/index.html
> +		<!-- Google Tag Manager -->
I understand, I just followed the instructions.

2024-10-19 00:28 UTC, AHReccese commented on public/index.html
> -		<noscript>You need to enable JavaScript to run this app.</noscript>
I thought it might not be very useful, but since it is kind of a rule, I put it back.

2024-10-19 10:05 UTC, sepandhaghighi approved these changes
🚀

2024-10-19 10:05 UTC, merged